#!/bin/bash
#SBATCH --job-name=clade_tree
#SBATCH --partition=savio2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=72:00:00
#SBATCH --mail-user=annen@berkeley.edu
#SBATCH --mail-type=ALL

working_dir=${1}    ## NLR_CTRL dir
species=${2}        ## Mo, Zt, Sc, or Nc
min_eco=${3}        ## was ~2/3 of the total number of accessions [adjust this first, ]
max_bl=${4}         ## was 0.5 (or 0.3 before that)
min_bl=${5}         ## was 0.05
min_bs=${6}         ## was 90

cd ${working_dir}
out_dir=TREESPLIT_OUT_${min_eco}_${max_bl}_${min_bl}_${min_bs}  ## create a unique directory for every different combination of parameters tried
mkdir -p ${out_dir}

module purge
source activate /global/scratch/users/annen/anaconda3/envs/R

### run autorefinement tree-splitting R script on each NLR clade
ls *NLR_Clade*.fa | awk -v FS="." '{ print $2; }' | while read clade; do
    Rscript /global/scratch/users/annen/KVKLab/fungal_srs/3.hv_analysis/autorefinement.R \
        --working_dir ${working_dir} \
        --tree_path CLADE_TREES/RAxML_bipartitionsBranchLabels.RAxML.${species}.${clade} \
        --alignment_path ${species}.${clade}.afa \
        --min_eco_overlap ${min_eco} \
        --max_branch_length ${max_bl} \
        --min_branch_length ${min_bl} \
        --min_bs_support ${min_bs} \
        --out_dir ${out_dir}
done

### run alignment filtering script to assess #hvsites of subalignments generated by tree splitting
mkdir -p ${out_dir}/SUBALIGNMENTS
cp ${out_dir}/*.subali.afa ${out_dir}/SUBALIGNMENTS
cd ${out_dir}/SUBALIGNMENTS
Rscript /global/scratch/users/annen/KVKLab/fungal_srs/3.hv_analysis/assess_aln_cutoff_dist.R \
    --working_dir . \
    --MinGapFraction 0.9 \
    --MinGapBlockWidth 3 #| awk '/subali.afa/ { print substr($2,2,length($2)-12) "\t" $3 "\t" substr($4,1,length($4)-1); }' > ${working_dir}/${out_dir}.HVSITE_RESULTS.txt

conda deactivate

